"""
encode_models.py – Run this ONCE locally to encode model files as base64 text.

Produces model_b64.py which git handles as plain text (no binary corruption).
The verify_models.py build script will decode them back during Render's build.

Usage:
    python encode_models.py
"""

import base64
import os

MODELS_DIR = os.path.join("services", "shadow_portfolio", "saved_models")
OUTPUT_FILE = os.path.join(MODELS_DIR, "model_b64.py")

FILES_TO_ENCODE = [
    "ppo_shadow_portfolio.zip",
    "vec_normalize.pkl",
]


def main():
    parts = []
    parts.append('"""Auto-generated by encode_models.py - DO NOT EDIT."""\n')
    parts.append("MODEL_DATA = {\n")

    for filename in FILES_TO_ENCODE:
        filepath = os.path.join(MODELS_DIR, filename)
        if not os.path.exists(filepath):
            print(f"  SKIP (not found): {filepath}")
            continue

        with open(filepath, "rb") as f:
            raw = f.read()

        encoded = base64.b64encode(raw).decode("ascii")
        size = len(raw)
        print(f"  Encoded: {filename} ({size} bytes -> {len(encoded)} chars b64)")

        parts.append(f'    "{filename}": (\n')
        # Split into 76-char lines for readability
        for i in range(0, len(encoded), 76):
            parts.append(f'        "{encoded[i:i+76]}"\n')
        parts.append("    ),\n")

    parts.append("}\n")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.writelines(parts)

    print(f"\nWritten to: {OUTPUT_FILE}")
    print("Now commit and push this file — it's plain text, git can't corrupt it.")


if __name__ == "__main__":
    main()
